exclude: ^(tests/unit/grades_report/test_csv_files/)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [-l=79, --profile=black, "."]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.2
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
