# This workflow will install Python dependencies, run tests and upload the coverage with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # sets up a Python environment for use in actions
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    # Install dependencies
    - name: Install pip, tox and coverage
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage

    # Python tests
    - name: Run Python tests
      run: make all-tests

    # Upload coverage
    - name: Upload the coverage to Codecov
      # Link for reference: https://github.com/codecov/codecov-action
      uses: codecov/codecov-action@v3
      with:
        flags: all-tests
        name: coverage
        fail_ci_if_error: true
